rootPath: "/esail3/Tackang/97CarsenseData/"
folderList:
  # - "210803_Suwon_Ginkgo"
  # - "210803_Suwon_Zelkova"
  # - "210811_Suwon_Zelkova"
  # - "210811_Suwon_Prunus"
  # - "210811_Suwon_Mixed"
  # - "210826_Suwon_Mixed1"
  # - "210826_Suwon_Mixed2"
  # - "210826_Suwon_Mixed3"
  # - "210830_Suwon_Mixed1"
  # - "210910_Suwon_Mixed1"
  # - "210924_Suwon_Mixed1"
  # - "210924_Suwon_Mixed2"
  # - "210924_Suwon_Mixed3"
  # - "210924_Suwon_Mixed4"
  # - "210927_Suwon_Mixed1"
  # - "210927_Suwon_Mixed2"
  # - "210927_Suwon_Mixed3"
  # - "211001_Suwon_Mixed1"
  # - "211001_Suwon_Mixed2"
  # - "211001_Suwon_Mixed4"
  # - "211001_Suwon_Mixed5"
  # - "211013_Suwon_Mixed1"
  # - "211013_Suwon_Mixed2", 이 폴더 문제있음 빈 이미지파일 0kb 이아래로 다 tkys 점검 필요
  # - "211013_Suwon_Mixed3"
  # - "211013_Suwon_Mixed4"
  # - "211021_Suwon_Mixed1"
  # - "211021_Suwon_Mixed2"
  # - "230428_Suwon_Zone1"
  # - "230428_Suwon_Zone2"
  - "230827_Suwon_1200hr"
  - "230827_Suwon_1500hr"
